### ISSUE TITLE
Allow removal of some case transforms

### ISSUE THREAD

**Issue by bagage** [Akanksha872/changeCaseVsExtension#1]
Thanks for this extension!

Would it be possible to add a (json) settings to allow user to customize which case transformations are available? 

I'd like to keep only a subset of all supported ones, since I will never use others (eg. Pascal one): the bigger list is, the harder to spot the case transformation I'm looking for.

Thanks!

**Comment by Akanksha872** [comment]
Hi, thanks for the valuable suggestion. The suggested Customization option has been added to the extension version **1.0.1**
